# Generated by Django 6.0.2 on 2026-04-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_user_uploaded',
            field=models.BooleanField(default=False, help_text='True если фильм загружен пользователем'),
        ),
    ]
