# Generated by Django 6.0.4 on 2026-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options_movie_author_movie_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL для вставки видео через iframe', null=True),
        ),
    ]
