# Generated by Django 6.0.4 on 2026-04-29 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_is_user_uploaded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL', max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='movies_movi_slug_5ef9c7_idx'),
        ),
    ]
